version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: systemdesign:latest
    container_name: app
    depends_on:
      - db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/files-system
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_JPA_HIBERNATE_DDL-AUTO=update
        - SPRING_DATASOURCE_INITIALIZE=true
        - SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION=true
        - SPRING_SQL_INIT_MODE=always
        - SPRING_SQL_INIT_DATA-LOCATIONS=classpath:data.sql
        - SPRING_JPA_GENERATE-DDL=true
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=files-system
